# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'laser_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(552, 258)
        MainWindow.setStyleSheet("background-color: rgb(255, 223, 140);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 40, 431, 101))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.StopfireButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.StopfireButton.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.StopfireButton.setObjectName("StopfireButton")
        self.gridLayout.addWidget(self.StopfireButton, 2, 1, 1, 1)
        self.ArmButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ArmButton.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.ArmButton.setObjectName("ArmButton")
        self.gridLayout.addWidget(self.ArmButton, 1, 0, 1, 1)
        self.DisarmButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.DisarmButton.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.DisarmButton.setObjectName("DisarmButton")
        self.gridLayout.addWidget(self.DisarmButton, 1, 1, 1, 1)
        self.FireButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.FireButton.setStyleSheet("background-color: rgb(81, 255, 51);")
        self.FireButton.setObjectName("FireButton")
        self.gridLayout.addWidget(self.FireButton, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 10, 341, 21))
        self.label.setStyleSheet("background-color: rgb(184, 227, 255)")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.Clock = QtWidgets.QLCDNumber(self.centralwidget)
        self.Clock.setGeometry(QtCore.QRect(30, 140, 211, 61))
        self.Clock.setObjectName("Clock")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.StopfireButton.setText(_translate("MainWindow", "STOP FIRE"))
        self.ArmButton.setText(_translate("MainWindow", "ARM"))
        self.DisarmButton.setText(_translate("MainWindow", "DISARM"))
        self.FireButton.setText(_translate("MainWindow", "FIRE"))
        self.label.setText(_translate("MainWindow", "CONTROL LASER 100 Hz  "))
